import type { Lang } from "@/lib/types";

const EN = {
  "nav.how": "How it works",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.support": "Support team",
  "nav.report": "Report help",
  "nav.call": "Call now",
  "nav.menu": "Menu",
  "nav.close": "Close",
  "lang.label": "Language",
  "home.kicker": "Relief mesh · flood week",
  "home.title.1": "Name the place. The",
  "home.title.2": "ranks the need.",
  "home.clerk": "clerk",
  "home.lede":
    "Aasra is the public door to a sector control room. A household writes a landmark and a need. A duty clerk — not a rumour thread — studies the sentence, sets severity, and points the nearest government desk, NGO, or volunteer. Officers see one queue.",
  "home.doors":
    "Three doors, in this order: report help with no account, apply as support with an ID photo, then the admin portal for people already on the allow-list. Google is only for the last two.",
  "home.pipeline": "See the pipeline",
  "home.board": "Duty board",
  "home.pick": "Pick the door that matches you. Do not sign in to file a public report.",
  "home.d1": "Report help",
  "home.d1n": "No login. Place, need, optional name. The clerk studies it.",
  "home.d2": "Support team",
  "home.d2n": "Government or NGO ID first. After a pass, Google with that Gmail.",
  "home.d3": "Admin portal",
  "home.d3n": "Allow-listed officers only. Google popup. Not for the public.",
  "home.adminBusy": "Waiting for Google…",
  "home.admin": "Admin portal",
  "home.mast": "Krishna delta edition",
  "footer.three": "Three doors",
  "footer.report": "Report help — no login",
  "footer.join": "Support team — ID + area",
  "footer.admin": "Admin — allow-list Google",
  "footer.mesh": "The mesh",
  "footer.how": "How a ticket is ranked",
  "footer.about": "About ReliefMesh",
  "footer.contact": "Contact",
  "footer.write": "Write",
  "footer.mail":
    "Applications and decisions go out from this inbox. Do not send medical emergencies here — call local services first.",
  "footer.tag": "Prepare · Respond · Rebuild",
  "footer.demo": "Demo sector control — not a substitute for 112 / 108",
  "footer.blurb":
    "ReliefMesh for a Krishna-delta flood sector: public reports, a Featherless clerk, verified field teams, and officers who rank one queue.",
  "report.kicker": "Public intake",
  "report.title": "Report help",
  "report.lede":
    "Type a place and choose from the five names, or drop a pin. Name is optional. Send is instant — the clerk studies it in the background.",
  "report.name": "Your name (optional)",
  "report.namePh": "If you want to be reached",
  "report.need": "What is needed",
  "report.needPh": "Blankets, boat, water, medical…",
  "report.send": "Send to desk",
  "report.sending": "Sending…",
  "report.demo": "Demo report",
  "report.ok": "Desk has the ticket. The nearest team sees it as recommended.",
  "report.loc": "Location",
  "join.kicker": "Application desk",
  "join.title": "Support team",
  "join.lede":
    "Three files. Government, NGO, or volunteer. Photograph the card, pick where you are from (top five suggestions), wait for the stamp. After a pass you land on your own desk.",
  "join.open": "Open this file →",
  "console.out": "Sign out",
  "console.reset": "Reset seed",
} as const;

export type CopyKey = keyof typeof EN;

const HI: Record<CopyKey, string> = {
  "nav.how": "कैसे काम करता है",
  "nav.about": "परिचय",
  "nav.contact": "संपर्क",
  "nav.support": "सहायता दल",
  "nav.report": "मदद दर्ज करें",
  "nav.call": "अभी कॉल करें",
  "nav.menu": "मेनू",
  "nav.close": "बंद",
  "lang.label": "भाषा",
  "home.kicker": "राहत जाल · बाढ़ सप्ताह",
  "home.title.1": "जगह बताइए।",
  "home.title.2": "ज़रूरत का क्रम तय करता है।",
  "home.clerk": "क्लर्क",
  "home.lede":
    "Aasra क्षेत्र नियंत्रण कक्ष का सार्वजनिक द्वार है। घर एक जगह और ज़रूरत लिखता है। ड्यूटी क्लर्क वाक्य पढ़कर गंभीरता तय करता है और निकटतम सरकारी डेस्क, एनजीओ या स्वयंसेवक की ओर इशारा करता है। अधिकारी एक कतार देखते हैं।",
  "home.doors":
    "तीन द्वार: बिना खाते मदद दर्ज करें, पहचान पत्र से सहायता दल के लिए आवेदन, फिर अनुमति-सूची वाले अधिकारियों का पोर्टल। Google केवल आखिरी दो के लिए है।",
  "home.pipeline": "पाइपलाइन देखें",
  "home.board": "ड्यूटी बोर्ड",
  "home.pick": "अपना द्वार चुनें। सार्वजनिक रिपोर्ट के लिए साइन इन न करें।",
  "home.d1": "मदद दर्ज करें",
  "home.d1n": "लॉगिन नहीं। जगह, ज़रूरत, वैकल्पिक नाम। क्लर्क पढ़ता है।",
  "home.d2": "सहायता दल",
  "home.d2n": "पहले सरकारी या एनजीओ पहचान। मंज़ूरी के बाद उसी जीमेल से Google।",
  "home.d3": "एडमिन पोर्टल",
  "home.d3n": "केवल अनुमति-सूची अधिकारी। Google पॉपअप। जनता के लिए नहीं।",
  "home.adminBusy": "Google की प्रतीक्षा…",
  "home.admin": "एडमिन पोर्टल",
  "home.mast": "कृष्णा डेल्टा संस्करण",
  "footer.three": "तीन द्वार",
  "footer.report": "मदद दर्ज करें — बिना लॉगिन",
  "footer.join": "सहायता दल — पहचान + क्षेत्र",
  "footer.admin": "एडमिन — अनुमति-सूची Google",
  "footer.mesh": "जाल",
  "footer.how": "टिकट कैसे रैंक होता है",
  "footer.about": "ReliefMesh के बारे में",
  "footer.contact": "संपर्क",
  "footer.write": "लिखें",
  "footer.mail":
    "आवेदन और निर्णय इस इनबॉक्स से जाते हैं। चिकित्सीय आपात यहाँ न भेजें — पहले स्थानीय सेवाओं को कॉल करें।",
  "footer.tag": "तैयारी · प्रतिक्रिया · पुनर्निर्माण",
  "footer.demo": "डेमो क्षेत्र नियंत्रण — 112 / 108 का विकल्प नहीं",
  "footer.blurb":
    "कृष्णा-डेल्टा बाढ़ क्षेत्र के लिए ReliefMesh: सार्वजनिक रिपोर्ट, क्लर्क, सत्यापित टीमें, और एक कतार।",
  "report.kicker": "सार्वजनिक इनटेक",
  "report.title": "मदद दर्ज करें",
  "report.lede":
    "जगह लिखें और पाँच नामों में से चुनें, या पिन गिराएँ। नाम वैकल्पिक है। भेजना तुरंत है — क्लर्क पीछे पढ़ता है।",
  "report.name": "आपका नाम (वैकल्पिक)",
  "report.namePh": "अगर संपर्क चाहिए",
  "report.need": "क्या चाहिए",
  "report.needPh": "कंबल, नाव, पानी, चिकित्सा…",
  "report.send": "डेस्क पर भेजें",
  "report.sending": "भेजा जा रहा है…",
  "report.demo": "डेमो रिपोर्ट",
  "report.ok": "डेस्क के पास टिकट है। निकटतम टीम को अनुशंसित दिखेगा।",
  "report.loc": "स्थान",
  "join.kicker": "आवेदन डेस्क",
  "join.title": "सहायता दल",
  "join.lede":
    "तीन फाइलें। सरकार, एनजीओ, या स्वयंसेवक। कार्ड की तस्वीर, जहाँ से हैं (पाँच सुझाव), मुहर का इंतज़ार। मंज़ूरी के बाद अपना डेस्क।",
  "join.open": "यह फाइल खोलें →",
  "console.out": "साइन आउट",
  "console.reset": "सीड रीसेट",
};

const TE: Record<CopyKey, string> = {
  "nav.how": "ఎలా పనిచేస్తుంది",
  "nav.about": "గురించి",
  "nav.contact": "సంప్రదించండి",
  "nav.support": "సహాయ బృందం",
  "nav.report": "సహాయం నమోదు",
  "nav.call": "ఇప్పుడు కాల్",
  "nav.menu": "మెనూ",
  "nav.close": "మూసివేయి",
  "lang.label": "భాష",
  "home.kicker": "రిలీఫ్ మెష్ · వరద వారం",
  "home.title.1": "చోటు చెప్పండి.",
  "home.title.2": "అవసరాన్ని క్రమం చేస్తుంది.",
  "home.clerk": "క్లర్క్",
  "home.lede":
    "ఆస్రా రంగ నియంత్రణ గదికి బహిరంగ ద్వారం. ఇల్లు ఒక ల్యాండ్‌మార్క్ మరియు అవసరం రాస్తుంది. డ్యూటీ క్లర్క్ వాక్యాన్ని చదివి తీవ్రత నిర్ణయించి సమీప ప్రభుత్వ డెస్క్, ఎన్‌జీఓ లేదా స్వచ్ఛంద సేవకుడిని చూపుతాడు. అధికారులు ఒక క్యూను చూస్తారు.",
  "home.doors":
    "మూడు ద్వారాలు: ఖాతా లేకుండా సహాయం నమోదు, ఐడీ ఫోటోతో సపోర్ట్ దరఖాస్తు, తర్వాత అనుమతి జాబితా అధికారుల పోర్టల్. Google చివరి రెండింటికే.",
  "home.pipeline": "పైప్‌లైన్ చూడండి",
  "home.board": "డ్యూటీ బోర్డు",
  "home.pick": "మీ ద్వారం ఎంచుకోండి. పబ్లిక్ రిపోర్ట్‌కు సైన్ ఇన్ చేయవద్దు.",
  "home.d1": "సహాయం నమోదు",
  "home.d1n": "లాగిన్ లేదు. చోటు, అవసరం, ఐచ్ఛిక పేరు. క్లర్క్ చదువుతాడు.",
  "home.d2": "సహాయ బృందం",
  "home.d2n": "ముందు ప్రభుత్వ లేదా ఎన్‌జీఓ ఐడీ. ఆమోదం తర్వాత అదే జీమెయిల్‌తో Google.",
  "home.d3": "అడ్మిన్ పోర్టల్",
  "home.d3n": "అనుమతి జాబితా అధికారులు మాత్రమే. Google పాపప్. ప్రజల కోసం కాదు.",
  "home.adminBusy": "Google కోసం వేచి…",
  "home.admin": "అడ్మిన్ పోర్టల్",
  "home.mast": "కృష్ణా డెల్టా ఎడిషన్",
  "footer.three": "మూడు ద్వారాలు",
  "footer.report": "సహాయం నమోదు — లాగిన్ లేదు",
  "footer.join": "సహాయ బృందం — ఐడీ + ప్రాంతం",
  "footer.admin": "అడ్మిన్ — అనుమతి జాబితా Google",
  "footer.mesh": "మెష్",
  "footer.how": "టికెట్ ఎలా ర్యాంక్ అవుతుంది",
  "footer.about": "ReliefMesh గురించి",
  "footer.contact": "సంప్రదించండి",
  "footer.write": "రాయండి",
  "footer.mail":
    "దరఖాస్తులు మరియు నిర్ణయాలు ఈ ఇన్‌బాక్స్ నుండి వెళ్తాయి. వైద్య అత్యవసరాలను ఇక్కడ పంపవద్దు — ముందు స్థానిక సేవలకు కాల్ చేయండి.",
  "footer.tag": "సిద్ధం · స్పందన · పునర్నిర్మాణం",
  "footer.demo": "డెమో సెక్టార్ నియంత్రణ — 112 / 108కు ప్రత్యామ్నాయం కాదు",
  "footer.blurb":
    "కృష్ణా-డెల్టా వరద రంగానికి ReliefMesh: పబ్లిక్ రిపోర్టులు, క్లర్క్, ధృవీకరించిన బృందాలు, ఒక క్యూ.",
  "report.kicker": "పబ్లిక్ ఇన్‌టేక్",
  "report.title": "సహాయం నమోదు",
  "report.lede":
    "చోటు టైప్ చేసి ఐదు పేర్లలో ఎంచుకోండి, లేదా పిన్ వేయండి. పేరు ఐచ్ఛికం. పంపడం తక్షణం — క్లర్క్ వెనుక చదువుతాడు.",
  "report.name": "మీ పేరు (ఐచ్ఛికం)",
  "report.namePh": "సంప్రదించాలంటే",
  "report.need": "ఏమి కావాలి",
  "report.needPh": "దుప్పట్లు, పడవ, నీరు, వైద్యం…",
  "report.send": "డెస్క్‌కు పంపండి",
  "report.sending": "పంపుతోంది…",
  "report.demo": "డెమో రిపోర్ట్",
  "report.ok": "డెస్క్‌కు టికెట్ ఉంది. సమీప బృందానికి సిఫార్సు కనిపిస్తుంది.",
  "report.loc": "స్థానం",
  "join.kicker": "దరఖాస్తు డెస్క్",
  "join.title": "సహాయ బృందం",
  "join.lede":
    "మూడు ఫైళ్లు. ప్రభుత్వం, ఎన్‌జీఓ, లేదా స్వచ్ఛంద సేవకుడు. కార్డు ఫోటో, మీరు ఎక్కడి నుండి (ఐదు సూచనలు), ముద్ర కోసం వేచి. ఆమోదం తర్వాత మీ డెస్క్.",
  "join.open": "ఈ ఫైల్ తెరవండి →",
  "console.out": "సైన్ అవుట్",
  "console.reset": "సీడ్ రీసెట్",
};

export const COPY: Record<Lang, Record<CopyKey, string>> = {
  en: EN,
  hi: HI,
  te: TE,
};
