import type { ResourceAsset } from "@/lib/types";

export const SEED_RESOURCES: ResourceAsset[] = [
  {
    id: "T4",
    callsign: "Team 4 NDRF",
    kind: "team",
    skills: ["flood-rescue", "boat-ops"],
    equipment: ["flood-rescue gear", "throwbags"],
    locationId: "W12",
    status: "free",
  },
  {
    id: "T1",
    callsign: "Team 1 Swift",
    kind: "team",
    skills: ["evac", "search"],
    equipment: ["boats", "lifejackets"],
    locationId: "W3",
    status: "free",
  },
  {
    id: "MED-A",
    callsign: "Med Cell A",
    kind: "medical",
    skills: ["nurse", "trauma"],
    equipment: ["ALS kits"],
    locationId: "W9",
    status: "free",
  },
  {
    id: "MED-B",
    callsign: "Med Cell B",
    kind: "medical",
    skills: ["doctor", "nurse"],
    equipment: ["field clinic"],
    locationId: "HOSP",
    status: "free",
  },
  {
    id: "TRK-3",
    callsign: "Truck 3",
    kind: "vehicle",
    skills: ["haul"],
    equipment: ["3-ton lorry"],
    locationId: "W19",
    status: "free",
  },
  {
    id: "TRK-7",
    callsign: "Truck 7",
    kind: "vehicle",
    skills: ["haul"],
    equipment: ["blankets bay"],
    locationId: "W14",
    status: "free",
  },
  {
    id: "WT-2",
    callsign: "Tanker 2",
    kind: "vehicle",
    skills: ["water"],
    equipment: ["water tanker"],
    locationId: "W11",
    status: "free",
  },
  {
    id: "GEN-1",
    callsign: "Genset 1",
    kind: "supply",
    skills: ["power"],
    equipment: ["62kVA generator"],
    locationId: "W7",
    status: "free",
  },
  {
    id: "BOAT-5",
    callsign: "Boat 5",
    kind: "vehicle",
    skills: ["rescue"],
    equipment: ["boats", "flood-rescue gear"],
    locationId: "W5",
    status: "free",
  },
  {
    id: "AMB-1",
    callsign: "Ambulance 1",
    kind: "medical",
    skills: ["nurse", "evac"],
    equipment: ["ambulance"],
    locationId: "HOSP",
    status: "free",
  },
];
