import type { InfraAsset, ResourceAsset } from "@/lib/types";

export const SEED_RESOURCES: ResourceAsset[] = [
  {
    id: "T4",
    callsign: "Team 4 NDRF",
    kind: "team",
    skills: ["flood-rescue", "boat-ops"],
    equipment: ["flood-rescue gear", "throwbags"],
    locationId: "W12",
    status: "free",
  },
  {
    id: "T1",
    callsign: "Team 1 Swift",
    kind: "team",
    skills: ["evac", "search"],
    equipment: ["boats", "lifejackets"],
    locationId: "W3",
    status: "free",
  },
  {
    id: "MED-A",
    callsign: "Med Cell A",
    kind: "medical",
    skills: ["nurse", "trauma"],
    equipment: ["ALS kits"],
    locationId: "W9",
    status: "free",
  },
  {
    id: "MED-B",
    callsign: "Med Cell B",
    kind: "medical",
    skills: ["doctor", "nurse"],
    equipment: ["field clinic"],
    locationId: "HOSP",
    status: "free",
  },
  {
    id: "MED-C",
    callsign: "Med Cell C",
    kind: "medical",
    skills: ["nurse", "evac"],
    equipment: ["ALS kits"],
    locationId: "W21",
    status: "free",
  },
  {
    id: "TRK-3",
    callsign: "Truck 3",
    kind: "vehicle",
    skills: ["haul"],
    equipment: ["3-ton lorry"],
    locationId: "W19",
    status: "free",
  },
  {
    id: "TRK-7",
    callsign: "Truck 7",
    kind: "vehicle",
    skills: ["haul"],
    equipment: ["blankets bay"],
    locationId: "W14",
    status: "free",
  },
  {
    id: "WT-1",
    callsign: "Tanker 1",
    kind: "vehicle",
    skills: ["water"],
    equipment: ["water tanker"],
    locationId: "W12",
    status: "free",
  },
  {
    id: "WT-2",
    callsign: "Tanker 2",
    kind: "vehicle",
    skills: ["water"],
    equipment: ["water tanker"],
    locationId: "W11",
    status: "free",
  },
  {
    id: "WT-4",
    callsign: "Tanker 4",
    kind: "vehicle",
    skills: ["water"],
    equipment: ["water tanker"],
    locationId: "W19",
    status: "free",
  },
  {
    id: "GEN-1",
    callsign: "Genset 1",
    kind: "supply",
    skills: ["power"],
    equipment: ["62kVA generator"],
    locationId: "W7",
    status: "free",
  },
  {
    id: "BOAT-1",
    callsign: "Boat 1",
    kind: "vehicle",
    skills: ["rescue", "boat-ops"],
    equipment: ["boats", "lifejackets"],
    locationId: "W21",
    status: "free",
  },
  {
    id: "BOAT-2",
    callsign: "Boat 2",
    kind: "vehicle",
    skills: ["rescue"],
    equipment: ["boats", "throwbags"],
    locationId: "W14",
    status: "free",
  },
  {
    id: "BOAT-5",
    callsign: "Boat 5",
    kind: "vehicle",
    skills: ["rescue"],
    equipment: ["boats", "flood-rescue gear"],
    locationId: "W5",
    status: "free",
  },
  {
    id: "BOAT-8",
    callsign: "Boat 8",
    kind: "vehicle",
    skills: ["rescue", "boat-ops"],
    equipment: ["boats"],
    locationId: "W9",
    status: "free",
  },
  {
    id: "AMB-1",
    callsign: "Ambulance 1",
    kind: "medical",
    skills: ["nurse", "evac"],
    equipment: ["ambulance"],
    locationId: "HOSP",
    status: "free",
  },
];

export const SEED_INFRA: InfraAsset[] = [
  {
    id: "INF-NH16",
    name: "NH-16 Autonagar underpass",
    kind: "road",
    roadId: "NH16",
    damage: 7,
    traffic: 9,
    hospitalAccess: 6,
    evacRoute: 8,
    population: 8,
    status: "open",
    rank: 0,
    score: 0,
    reason: "",
    consequences: [],
    updatedAt: 0,
  },
  {
    id: "INF-PRAK",
    name: "Prakasam barrage road",
    kind: "bridge",
    roadId: "PRAKASAM",
    damage: 8,
    traffic: 7,
    hospitalAccess: 5,
    evacRoute: 9,
    population: 7,
    status: "open",
    rank: 0,
    score: 0,
    reason: "",
    consequences: [],
    updatedAt: 0,
  },
  {
    id: "INF-KANAKA",
    name: "Kanakadurga flyover",
    kind: "flyover",
    roadId: "KANAKA",
    damage: 4,
    traffic: 8,
    hospitalAccess: 10,
    evacRoute: 9,
    population: 6,
    status: "open",
    rank: 0,
    score: 0,
    reason: "",
    consequences: [],
    updatedAt: 0,
  },
  {
    id: "INF-ELURU",
    name: "Eluru Road",
    kind: "road",
    roadId: "ELURU",
    damage: 5,
    traffic: 7,
    hospitalAccess: 4,
    evacRoute: 6,
    population: 8,
    status: "open",
    rank: 0,
    score: 0,
    reason: "",
    consequences: [],
    updatedAt: 0,
  },
  {
    id: "INF-BANDAR",
    name: "Bandar Road",
    kind: "road",
    roadId: "BANDAR",
    damage: 3,
    traffic: 8,
    hospitalAccess: 9,
    evacRoute: 7,
    population: 7,
    status: "open",
    rank: 0,
    score: 0,
    reason: "",
    consequences: [],
    updatedAt: 0,
  },
  {
    id: "INF-PUMP",
    name: "Canal service road",
    kind: "road",
    roadId: "PUMP",
    damage: 6,
    traffic: 3,
    hospitalAccess: 2,
    evacRoute: 7,
    population: 5,
    status: "open",
    rank: 0,
    score: 0,
    reason: "",
    consequences: [],
    updatedAt: 0,
  },
];
